name: CI
on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  ci:
    uses: millsydotdev/.github/.github/workflows/ci-rust.yml@main
    with:
      release: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
